services:
  postgres:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: car_rental_db
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgrespw
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - postgres

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
